### ISSUE TITLE
authorized_keys ending up in root and not in owner's

### ISSUE THREAD

**Issue by zeridon** [Oefenweb/ansible-ssh-keys#26]
# What is the problem
When defining multiple users and authorized keys, the keys end up in /root/.ssh/authorized_keys and not in ~/.ssh/authorized_keys

# Expected
Keys are added to the coresponding autorized_keys file (in users home dir)

# What is happening
Keys end up in root's authorized_keys file and the file is not owned by root but by the last owner of the key

Role version: `oefenweb.ssh_keys, v3.0.1`
Ansible version:  `ansible 2.9.6`

# Steps to reproduce
**site.yml**
```
---
- hosts: all
  roles:
    - role: oefenweb.user
    - role: oefenweb.ssh_keys
```

**group_vars/all.yml**
```
---
# User declarations (oefenweb.user)
user_users:
  # ansible for automation
  - name: ansible
    comment: Ansible automation user
    password: xxx
    update_password: always
    append: true
    groups:
      - sudo
      - adm

  - name: user1
    comment: user1
    password: xxxx
    append: true
    groups:
      - sudo
      - adm
    update_password: on_create

  - name: user2
    comment: user2
    password: xxxx
    append: true
    groups:
      - sudo
      - adm
    update_password: on_create

# authorized keys (oefenweb.ssh_keys)
ssh_keys_authorized_keys:
  - owner: ansible
    src: files/keys/ansible-id_rsa.pub
  - owner: user1
    src: files/keys/user1-id_rsa.pub
  - owner: user2
    src: files/keys/user2-id_ecdsa.pub
```

# End result
```
root@WEB-TEST2:~# ls -la /root/.ssh/authorized_keys 
-rw------- 1 user2 user2 2776 Jul  5 10:32 /root/.ssh/authorized_keys

root@WEB-TEST2:~# wc -l /root/.ssh/authorized_keys 
3 /root/.ssh/authorized_keys

root@WEB-TEST2:~# ls -l /home/ansible/.ssh/
total 0
```

# Debug output
```
TASK [oefenweb.ssh_keys : authorized-keys | set up for users] *****************************************************************************************************************************************************
task path: /home/zeridon/.ansible/roles/oefenweb.ssh_keys/tasks/authorized-keys.yml:3
ok: [test-web-2] => (item={'owner': 'ansible', 'src': 'files/keys/ansible-id_rsa.pub'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "comment": null,
    "exclusive": false,
    "follow": false,
    "gid": 1007,
    "group": "user2"
    "invocation": {
        "module_args": {
            "comment": null,
            "exclusive": false,
            "follow": false,
            "key": "ssh-rsa XXXX REDACTED XXXX",
            "key_options": null,
            "keyfile": "/root/.ssh/authorized_keys",
            "manage_dir": true,
            "path": "/root/.ssh/authorized_keys",
            "state": "present",
            "user": "ansible",
            "validate_certs": true
        }
    },
    "item": {
        "owner": "ansible",
        "src": "files/keys/ansible-id_rsa.pub"
    },
    "key": "ssh-rsa XXXX REDACTED XXXX",
    "key_options": null,
    "keyfile": "/root/.ssh/authorized_keys",
    "manage_dir": true,
    "mode": "0600",
    "owner": "user2",
    "path": "/root/.ssh/authorized_keys",
    "size": 2776,
    "state": "file",
    "uid": 1007,
    "user": "ansible",
    "validate_certs": true
}
```
